### ISSUE TITLE
'str' object has no attribute 'read' 

### ISSUE THREAD

**Issue by TempleOfHorus** [LukeFZ/CikExtractor#1]
Hello. I got error: 'str' object has no attribute 'read' 
![1](https://user-images.githubusercontent.com/60355056/219939764-18a4cc83-2f54-4f04-bc3a-1a65cd0d3091.jpg)
Any solution ?

**Comment by LukeFZ** [comment]
- Which version of Python and Qiling do you have installed? (Python 3.10 + Qiling 1.4.5 are confirmed working, have not tested 3.11)
- What version of Windows are you running?
- What's the SHA256 hash of the clipsp.sys file at Emulation/clipsp.sys?

**Comment by LukeFZ** [comment]
Weird, I can't find any version of clipsp.sys with that SHA256 hash. 
- Which specific version of Windows 11 is this? 
- Could you check the version of the .sys file in C:\Windows\System32\drivers and send the file SHA256 + file version?

You can also attempt to run these commands (Administrator needed) inside of the Emulation folder, which should dump the registry hives it's complaining about so the script can access them (Taken from the Qiling dllscollector.bat script):
```
SET QL_REGDIR64="x8664_windows\registry"
REG SAVE HKLM\SYSTEM %QL_REGDIR64%\SYSTEM /Y
REG SAVE HKLM\SECURITY %QL_REGDIR64%\SECURITY /Y
REG SAVE HKLM\SOFTWARE %QL_REGDIR64%\SOFTWARE /Y
REG SAVE HKLM\HARDWARE %QL_REGDIR64%\HARDWARE /Y
REG SAVE HKLM\SAM %QL_REGDIR64%\SAM /Y
COPY /B /Y C:\Users\Default\NTUSER.DAT "%QL_REGDIR64%\NTUSER.DAT"
```

**Comment by TempleOfHorus** [comment]
Oh, I did hash of diferrent file. Here is hash of clipsp.sys (is same for in emulation/drivers folder): 6109cead2a0813fbc75d8832b64d3abb5a953a6f7ce0fd1229223913d019ea61

1. Windows 11 Pro

I ran commands, same error.

**Comment by LukeFZ** [comment]
Alright, reproduced and fixed the issue. Please try the [new release](https://github.com/LukeFZ/CikExtractor/releases/tag/v1.0.1) (important: extract into a new directory!) and report back if it worked for you.

**Comment by TempleOfHorus** [comment]
I still get the same error: 'str' object has no attribute 'read'

**Comment by TempleOfHorus** [comment]
> Alright, reproduced and fixed the issue. Please try the [new release](https://github.com/LukeFZ/CikExtractor/releases/tag/v1.0.1) (important: extract into a new directory!) and report back if it worked for you.

Works! Thank you :)

**Comment by TempleOfHorus** [comment]
Do you have discord or email where I can contact you privately ?

**Comment by LukeFZ** [comment]
You can contract me on discord, LukeFZ#4035

**Comment by Blackbird88** [comment]
I am getting the same error, but the hash of the clipsp.sys file is 0aa17eda11758971a1035e883069fc49fd56b93d145856b4f177eb354ae2986b
![image](https://github.com/LukeFZ/CikExtractor/assets/4414625/6a08fba4-14fb-48c2-8a44-bb0c7494efe2)
