### ISSUE TITLE
CIKs for Xbox Games aren't getting dumped

### ISSUE THREAD

**Issue by p12h4** [LukeFZ/CikExtractor#3]
Hello, I was trying to extract the CIKs for some Xbox Games, but I have noticed that the CIKs are not being dumped properly.

It seems that the tool is unable to extract CIKs for Xbox games, even though it is able to extract CIKs for Microsoft Store apps, which leads me to believe that it might use a different system for Xbox games than it does for Microsoft Store apps.

**Comment by LukeFZ** [comment]
If you are referring to games installed from the Xbox app, these keys are in fact getting dumped properly as I have tested the tool with those games myself. If you ran the tool prior to installing the game, you need to remove the `control_export.reghive` file from the CikExtractor directory to make it re-export the hive and dump the newly added keys.

**Comment by LukeFZ** [comment]
Just tried it on my device, and after starting the download of Minecraft Dungeons from the Xbox app the tool does dump its CIK correctly - seems like this is an issue on your device. Try starting the game once prior to running the tool, this might cause WIndows to obtain a new license if it doesn't have one with the key already loaded.

**Comment by p12h4** [comment]
After trying around for a bit it appears to work now... It was seemingly skipping xbox games but it is dumping them now. I still don't know what caused it, though.
