### ISSUE TITLE
Is it actually possible to directly extract the decryption key from the msixvc file without going through the kernel bridge, registry or something like that?

### ISSUE THREAD

**Issue by FranzFischer78** [LukeFZ/CikExtractor#4]

**Comment by LukeFZ** [comment]
The .msixvc file doesn't contain the decryption key, only its associated content id which is used to retrieve your game license from microsofts servers. While you could emulate the process of obtaining the license and parsing that directly to get the CIK (see my xvdtool fork for how to parse licenses), you'd still need your device key to decrypt/unwrap the actual CIK for which you need access to the registry anyway.

**Comment by FranzFischer78** [comment]
What's exactly the role of the device key in the decryption process?

**Comment by LukeFZ** [comment]
The CIKs in the license are wrapped (AES Key Wrap, https://www.rfc-editor.org/rfc/rfc3394) using the device key, meaning that only the device whose device key matches the one used for wrapping can unwrap (= decrypt) the key and get the actual CIK.

**Comment by dktapps** [comment]
The API that the license is downloaded from would have to know your device key to be able to encrypt the CIK though, right? Shouldn't it be possible to just provide a user controlled key instead of OS one? Or is it more complicated

**Comment by totchi-lagawi** [comment]
> The .msixvc file doesn't contain the decryption key, only its associated content id which is used to retrieve your game license from microsofts servers. While you could emulate the process of obtaining the license and parsing that directly to get the CIK (see my xvdtool fork for how to parse licenses), you'd still need your device key to decrypt/unwrap the actual CIK for which you need access to the registry anyway.

I suppose it is actually possible to register a fake device, with a key controlled by the user. How would you actually obtain licenses? Microsoft's APIs are underdocumented when it comes to licenses.

**Comment by LukeFZ** [comment]
There is an endpoint https://licensing.mp.microsoft.com/v7.0/licenses/content that gets used by the store for requesting licenses (and entitlements), which you have to authenticate against using wlid/msa, send your requested product id and whether the license needs to contain the key or not. if you intercept the network requests sent during package installation / launching you will likely see requests to this url

**Comment by dktapps** [comment]
Does anyone know where in the registry the device key can be pulled from?

**Comment by LukeFZ** [comment]
Check the RegistryInterface class in the project, it contains the relevant paths that contain all licenses (which also includes the device license)
